### PR TITLE
v2.0 pull request

### PR DESCRIPTION
**Pull request by loader3229**
v2.0 pull request

I'm loader3229 (@qq1010903229) in bestdori.

I made this simulator to support new note types in JP server 5.0 new SP chart.

### CODE REVIEW

**Comment by thtl1999** [comment]
Wow! I didn't expected supporting this old project! I almost give up with my new simulator https://github.com/thtl1999/BanG-simulator

I will check this code and I will merge if it is ok

Thanks for your participation!

**Comment by loader3229** [comment]
Note: the font used in my version is bandori CN server font

**Comment by loader3229** [comment]
And you can see my v2.0 release

https://github.com/qq1010903229/BanG-simulator/releases/download/v2.0/release.zip

**Comment by loader3229** [comment]
JP server 5.0 new SP chart support

Curved Slide Support

image

Directional Flick Support (Note: Directional Flick sprite in my release has a problem, and no Directional Flick effect sprite)

image

**Comment by thtl1999** [comment]
@qq1010903229 

That is awesome!

I compiled gm file and saw it works

I'm going to merge this branch and change my repo readme to go to your github repo page (also release)

And I want to help you. I corrected tranparent background for your directional note. Please use this.

[corrected.zip](https://github.com/thtl1999/BanG-simulator/files/6986253/corrected.zip)

Thanks for your support!

**Comment by loader3229** [comment]
Can you get skill note effect sprites and directional flick note effect sprites?

**Comment by loader3229** [comment]
And try to play Setsuna Trip (セツナトリップ) SP (296+) in bandori GBP JP server

**Comment by loader3229** [comment]
or Fuwa-Fuwa Time (ふわふわ時間) SP (059+) in bandori GBP JP server

**Comment by thtl1999** [comment]
As mentioned in text file, the author of effect sprite is not me.

May be you can record GBP screen and get effect sprite there.

I tested special difficulty with directional note. It works well

I will merge then

**Pull request merged**
